export const data = {
  users: [
    {
      firstName: "User",
      lastName: "1",
      userName: "user_1",
      indexRef: 0,
      createdAt: "2018-03-28T00:53:08.981Z",
    },
    {
      firstName: "User",
      lastName: "2",
      userName: "user_2",
      indexRef: 1,
      createdAt: "2017-04-23T19:24:43.992Z",
    },
    {
      firstName: "User",
      lastName: "3",
      userName: "user_3",
      indexRef: 2,
      createdAt: "2020-07-29T03:50:46.143Z",
    },
    {
      firstName: "User",
      lastName: "4",
      userName: "user_4",
      indexRef: 3,
      createdAt: "2019-09-30T19:31:56.383Z",
    },
    {
      firstName: "User",
      lastName: "5",
      userName: "user_5",
      indexRef: 4,
      createdAt: "2015-05-04T21:11:19.982Z",
    },
    {
      firstName: "User",
      lastName: "6",
      userName: "user_6",
      indexRef: 5,
      createdAt: "2020-06-09T15:15:18.817Z",
    },
    {
      firstName: "User",
      lastName: "7",
      userName: "user_7",
      indexRef: 6,
      createdAt: "2017-07-28T00:30:32.214Z",
    },
    {
      firstName: "User",
      lastName: "8",
      userName: "user_8",
      indexRef: 7,
      createdAt: "2020-05-04T08:59:15.292Z",
    },
    {
      firstName: "User",
      lastName: "9",
      userName: "user_9",
      indexRef: 8,
      createdAt: "2019-10-07T20:17:43.678Z",
    },
  ],
  posts: [
    {
      title: "Et voluptatem nulla omnis et iusto ullam.",
      body: "Ad non pariatur. Aut molestias accusamus inventore sunt voluptates non doloremque illum. Perspiciatis et provident vel et fugiat dolores ut. Quos quibusdam impedit cupiditate quia at eaque.",
      userId: 9,
      indexRef: 0,
      createdAt: "2018-08-10T23:41:51.714Z",
    },
    {
      title:
        "Similique impedit consequatur qui ipsam sint quam rerum dolores distinctio.",
      body: "Quidem nisi saepe omnis quia repudiandae odio. Eius quia quis inventore. Illo nihil voluptas est. Quo atque facilis autem velit. Aspernatur quia labore eveniet dolorum.\n \rEum aut non modi.",
      userId: 1,
      indexRef: 1,
      createdAt: "2015-08-28T14:07:58.674Z",
    },
    {
      title: "Maiores ex tempore quo qui.",
      body: "Earum natus quis possimus iusto voluptatem dicta. Facilis voluptate minima architecto similique quas. Tempora illum omnis aut et id minima nihil itaque quo. Dicta ratione ut voluptates quia.",
      userId: 2,
      indexRef: 2,
      createdAt: "2016-06-05T20:17:46.223Z",
    },
    {
      title: "Autem non temporibus sequi.",
      body: "Ipsam blanditiis amet. Sapiente sed eos earum qui consequatur natus quia voluptatem nihil. Non eum omnis aut sed autem et recusandae vel. Explicabo et temporibus quod voluptatem debitis.",
      userId: 5,
      indexRef: 3,
      createdAt: "2021-04-01T01:06:47.589Z",
    },
    {
      title: "Velit culpa dolorem libero velit sed temporibus omnis.",
      body: "Laudantium accusamus sit excepturi aut voluptatem. Sed aliquam accusamus et dicta debitis. Quam nihil iusto ullam repudiandae.\n \rAutem aperiam officiis quia eius quis esse quos eos at.",
      userId: 8,
      indexRef: 4,
      createdAt: "2020-04-22T04:29:45.812Z",
    },
    {
      title: "Itaque voluptas et tempora dolor dolor amet dolor ut.",
      body: "Debitis praesentium facere odit similique in sed necessitatibus. Possimus quidem et. Aliquid labore placeat rerum hic nulla.\n \rEx incidunt qui quibusdam laboriosam consequatur accusantium.",
      userId: 2,
      indexRef: 5,
      createdAt: "2017-10-21T11:29:55.549Z",
    },
    {
      title: "Molestias nobis sunt eum totam.",
      body: "Consequatur natus quae quisquam laudantium est. Aut omnis autem nulla et ipsum sint. Et consectetur fugiat magni et laboriosam. Dolor magni vero magnam dignissimos sed iure qui voluptatem.",
      userId: 9,
      indexRef: 6,
      createdAt: "2015-12-11T00:40:59.233Z",
    },
    {
      title:
        "Repellendus fugiat officiis quisquam asperiores aliquid dignissimos.",
      body: "Quisquam quas quia rerum blanditiis autem. Odit harum possimus sit dolor voluptatem aliquid facilis corporis. Rerum magnam qui optio voluptates tenetur et totam qui occaecati. Libero et ut.",
      userId: 5,
      indexRef: 7,
      createdAt: "2021-04-23T08:30:50.947Z",
    },
    {
      title: "Ad nihil magni atque.",
      body: "Laudantium qui accusamus deleniti velit nulla eligendi harum maxime nobis. Vitae sint totam et. Ipsa totam est error est dolor nostrum aperiam tenetur unde. Sit labore dolores et dignissimos.",
      userId: 2,
      indexRef: 8,
      createdAt: "2016-06-07T15:31:52.589Z",
    },
    {
      title: "Doloremque sit atque dolor rem non ut voluptates quod maiores.",
      body: "Facere fugit voluptates dolor enim illo consequatur ipsa cupiditate. Assumenda minima facere ratione. Voluptas laborum ipsa eveniet impedit magnam in. Molestiae consectetur enim.",
      userId: 5,
      indexRef: 9,
      createdAt: "2020-03-27T17:21:33.103Z",
    },
    {
      title: "Nulla sunt sint et et officia voluptatem itaque.",
      body: "Quam voluptatem at reprehenderit nesciunt qui est aperiam aut voluptas. Deserunt maiores non rerum numquam impedit quibusdam maxime consequatur. Perspiciatis sit cumque tenetur accusantium.",
      userId: 4,
      indexRef: 10,
      createdAt: "2016-11-19T22:23:52.689Z",
    },
    {
      title: "Dolores consequatur eos in ipsa et quasi sequi.",
      body: "Non est earum omnis. Optio earum ex ut. Id quae voluptatem. Deleniti maxime aut voluptatem quasi placeat aliquid sunt.\n \rMolestiae quia et veniam provident quia. Sed et asperiores sed est.",
      userId: 2,
      indexRef: 11,
      createdAt: "2018-10-31T18:06:19.757Z",
    },
    {
      title: "Nemo rerum dolorem.",
      body: "Accusantium quis est molestiae. Aliquam voluptatem rerum eaque. Nihil error nam voluptates aut eum libero. Est quasi hic dolor itaque. Quis officia distinctio et non itaque. Voluptate odio.",
      userId: 2,
      indexRef: 12,
      createdAt: "2020-12-19T19:25:24.495Z",
    },
    {
      title: "Culpa consequatur dicta dignissimos.",
      body: "Animi perspiciatis aut quia laborum repellat. Nobis ut qui odit aliquid tenetur. Dolorem porro earum quisquam deleniti debitis fuga vel officiis. Veritatis sed sint. Qui reiciendis at illo.",
      userId: 9,
      indexRef: 13,
      createdAt: "2021-02-22T14:54:03.421Z",
    },
    {
      title:
        "Qui facere repellat dolor sint quos quam consequatur sed asperiores.",
      body: "Distinctio atque amet doloribus vero doloremque et est nobis. Vel molestiae quidem ut qui quasi quas officiis ut. Aut amet nihil asperiores repellendus eos. Sint amet odio itaque et.",
      userId: 6,
      indexRef: 14,
      createdAt: "2019-09-07T06:51:26.519Z",
    },
    {
      title: "Laborum optio sunt aut ut ut ut.",
      body: "Sit sed deserunt libero nulla in culpa. Culpa quasi ullam quaerat dolorem assumenda molestiae. Doloribus autem possimus beatae esse optio consectetur. Ut veritatis sint voluptatem minima.",
      userId: 8,
      indexRef: 15,
      createdAt: "2019-02-12T01:13:25.622Z",
    },
    {
      title: "lorem",
      body: "ipsum",
      userId: 1,
      indexRef: 16,
      createdAt: "2024-06-19T00:13:28.340Z",
    },
  ],
};
